version: "3"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  crypt_db:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - "5432/tcp"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: crypt_pg
  crypt_scan:
    build: ./crypt_scan
    volumes:
      - ./crypt_scan:/usr/src/crypt_scan
    depends_on:
      - crypt_db
    container_name: crypt_scan
  arbitrage_opp:
    build: ./arbitrage_opp
    volumes:
     - ./arbitrage_opp:/usr/src/arbitrage_opp
    depends_on:
     - crypt_db
     - crypt_scan
    container_name: arbitrage_opp
